config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'ideas#index'
  # root to: redirect('/ideas')
  get'search', to: 'ideas#search'
  resources :ideas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
   mount_uploader :picture, PictureUploader
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except:[:index]

  # GET /ideas or /ideas.json
  def index
    if user_signed_in?
      @pagy, @ideas = pagy(Idea.where(user_id: current_user),items:3)
    else
      @pagy, @ideas = pagy(Idea.order(created_at: :desc),items:3)
    end
  end

  # GET /ideas/1 or /ideas/1.json
  def show
  end

  def search
    @ideas = Idea.where("name LIKE?", "%" + params[:q] + "%")
  end

  # GET /ideas/new
  def new
    @idea = current_user.ideas.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas or /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)
    respond_to do |format|
      if @idea.save
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully created." }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1 or /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully updated." }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1 or /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: "Idea was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
       @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>
      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture %>
  </div>
  <br/>

  <div>
    <%= form.number_field :user_id, id: :idea_user_id, value: current_user.id, type: :hidden %>
  </div>
  <br/>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div class="<%= dom_id idea %>">
  <div class="well">
    <br>
      <h2><%= idea.name %></h2>
      <p><%= idea.description %></p>
  </div>
</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Show this idea", @idea %> |
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Ideas</h1>
<div id="ideas">
  <% @ideas.each do |idea| %>
  <%= render idea %>
    <%=link_to "Read More", idea, :class => 'btn btn-primary'%>
  <% end %>
</div>
<br/>
<br/>
 <%== pagy_bootstrap_nav(@pagy).html_safe %>

app/views/ideas/new.html.erb
<h1>New idea</h1>
<%= render "form", idea: @idea %>
<br>
<div>
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/search.html.erb
<br>
<h1> search Result </h1>
<% if @ideas.blank? %>
<p> No result found</p>
<% else %>
<%= render @ideas %>
<% end %>

app/views/ideas/show.html.erb
<%= render @idea %>
<%= image_tag(@idea.picture_url, width: "20%") if @idea.picture.present? %>
<br>
<br>
<div>
  <%= link_to "Edit", edit_idea_path(@idea), :class => 'btn btn-secondary' %>
  <%= button_to "Destroy", @idea, :method => :delete, :class => 'btn btn-danger' %>
  <%= link_to "Back", ideas_path, :class => 'btn btn-primary'%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGirls</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<div class="container-fluid">
  <a class="navbar-brand" href=#>The Idea App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item hover">
        <a class="nav-link" href="/ideas">Ideas</a>
      </li>
      <li class="nav-item hover">
        <a class="nav-link" href="/ideas/new">Add New Idea</a>
      </li>
      <li>
        <div class="container-fluid">
         <form class="form-inline my-2 my-lg-0" action="/search">
           <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search">
         </form>
        </div>
      </li>
    </ul>
      <% if user_signed_in? %>
        <span class="navbar-text">
         Logged in as <%= current_user.email %>
        </span>
          <%= link_to "Edit", edit_user_registration_path,:class => 'navbar-link',:class => "btn btn-primary" %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-primary" %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path,:class => 'navbar-link',:class => "btn btn-primary" %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link',:class => "btn btn-primary"  %>
      <% end %>
  </div>
 </div>
</nav>
<footer>
<div class="container">
  Rails Girls <%= Time.now.year %>
</div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<div class="container">
  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>
<div class="container">
<%= yield %>
</div>
  </body>
</html>